import express from "express";
import { CategoryController } from "../controllers/category.controller";
import CategoryService from "../services/category.service";
const router = express.Router();
router.route("/").post(CategoryController.create);
router.route("/addSub").post(CategoryController.createSub);
router.route("/getall").get(CategoryController.getAll);
router.route("/getallsub").get(CategoryController.getAllSub);
router.route("/:_id").put(CategoryController.update);
router.route("/subs/:_id").put(CategoryController.updateSub);
export default router;
