import express from "express";
import RoleRoute from "./role.route";
import AuthRoute from "./auth.route";
import ProductRoute from "./product.route";
import TrademarkRoute from "./trademark.route";
import CategoryRoute from "./category.route";
import commentRoute from "./comment.router";
import OrderRoute from "./order.route";
import UploadRoute from "./upload.router";
import TagRoute from "./tag.route";
const route = express.Router();
route.use("/role", RoleRoute);
route.use("/auth", AuthRoute);
route.use("/products", ProductRoute);
route.use("/trademark", TrademarkRoute);
route.use("/category", CategoryRoute);
route.use("/comment", commentRoute);
route.use("/order", OrderRoute);
route.use("/upload", UploadRoute);
route.use("/tag", TagRoute);
export default route;
